#!/bin/sh

echo "Running pre-commit checks..."

echo "Running unit tests with pnpm..."
pnpm --dir salarycalc test

if [ $? -ne 0 ]; then
  echo "❌ Tests failed. Commit aborted."
  exit 1
fi

echo "✅ Tests passed. Commit allowed."
exit 0